### ISSUE TITLE
[Bug] After last HA update addon won't start

### ISSUE THREAD

**Issue by Koterak** [tomaae/homeassistant-openmediavault#125]
When I try to add devices I got error. It happened after HA was updated to Python 3.11.

## How to reproduce the issue
Just try to add devices from OMV.

## Software versions
 - Home Assistant 2023.6.3
-  Supervisor 2023.06.2
-  Operating System 10.3
 - openmediavault integration version: v1.4.1
 - openmediavault software version: 6.4.3-1 (Shaitan)

## Traceback/Error logs

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmediavault/__init__.py", line 35, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 203, in async_update
    await self.hass.async_add_executor_job(self.get_compose)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmediavault/omv_controller.py", line 559, in get_compose
    if "data" not in tmp:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by tomaae** [comment]
I dont think this error coudl be related to HA update.
Can you run it in debug?

**Comment by BebeMischa** [comment]
just for reference, no issues here after latest backups
