### ISSUE TITLE
Division by zero-error, can't start integration

### ISSUE THREAD

**Issue by Skeletorjus** [tomaae/homeassistant-openmediavault#2]
## Describe the issue
The integration crashes on startup with a division by zero-error. See log.

## Software versions

 - Home Assistant version: HA v0.108.39
 - openmediavault integration version: v1.0.0
 - openmediavault software version: 4.1.35-1

## Traceback/Error logs
```
2020-04-27 10:34:59 DEBUG (SyncWorker_26) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.1.130 connected
2020-04-27 10:34:59 DEBUG (SyncWorker_26) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.1.130 query: System, getInformation, {}, {'updatelastaccess': False}
2020-04-27 10:35:00 DEBUG (SyncWorker_26) [custom_components.openmediavault.omv_api] OpenMediaVault 192.168.1.130 query response: {'response': [{'name': 'Hostname', 'value': 'myhost.workgroup', 'type': 'string', 'index': 0}, {'name': 'Version', 'value': '4.1.35-1 (Arrakis)', 'type': 'string', 'index': 1}, {'name': 'Processor', 'value': 'Intel(R) Xeon(R) CPU E3-1265L V2 @ 2.50GHz', 'type': 'string', 'index': 2}, {'name': 'Kernel', 'value': 'Linux 4.19.0-0.bpo.8-amd64', 'type': 'string', 'index': 3}, {'name': 'System time', 'value': 'Mon Apr 27 10:35:00 2020', 'type': 'string', 'index': 4}, {'name': 'Uptime', 'value': '11 days 22 hours 50 minutes 51 seconds', 'type': 'string', 'index': 5}, {'name': 'Load average', 'value': '3.46, 2.34, 2.31', 'type': 'string', 'index': 6}, {'name': 'CPU usage', 'value': {'text': '38%', 'value': 38.403041825095}, 'type': 'progress', 'index': 7}, {'name': 'Memory usage', 'value': {'text': '54% of 11.68 GiB', 'value': 54}, 'type': 'progress', 'index': 8}], 'error': None}
2020-04-27 10:35:00 DEBUG (SyncWorker_26) [custom_components.openmediavault.helper] Processing source [[{'name': 'Hostname', 'value': 'myhost.workgroup', 'type': 'string', 'index': 0}, {'name': 'Version', 'value': '4.1.35-1 (Arrakis)', 'type': 'string', 'index': 1}, {'name': 'Processor', 'value': 'Intel(R) Xeon(R) CPU E3-1265L V2 @ 2.50GHz', 'type': 'string', 'index': 2}, {'name': 'Kernel', 'value': 'Linux 4.19.0-0.bpo.8-amd64', 'type': 'string', 'index': 3}, {'name': 'System time', 'value': 'Mon Apr 27 10:35:00 2020', 'type': 'string', 'index': 4}, {'name': 'Uptime', 'value': '11 days 22 hours 50 minutes 51 seconds', 'type': 'string', 'index': 5}, {'name': 'Load average', 'value': '3.46, 2.34, 2.31', 'type': 'string', 'index': 6}, {'name': 'CPU usage', 'value': {'text': '38%', 'value': 38.403041825095}, 'type': 'progress', 'index': 7}, {'name': 'Memory usage', 'value': {'text': '54% of 11.68 GiB', 'value': 54}, 'type': 'progress', 'index': 8}]]
2020-04-27 10:35:00 DEBUG (SyncWorker_26) [custom_components.openmediavault.helper] Processing entry [{'name': 'Hostname', 'value': 'myhost.workgroup', 'type': 'string', 'index': 0}, {'name': 'Version', 'value': '4.1.35-1 (Arrakis)', 'type': 'string', 'index': 1}, {'name': 'Processor', 'value': 'Intel(R) Xeon(R) CPU E3-1265L V2 @ 2.50GHz', 'type': 'string', 'index': 2}, {'name': 'Kernel', 'value': 'Linux 4.19.0-0.bpo.8-amd64', 'type': 'string', 'index': 3}, {'name': 'System time', 'value': 'Mon Apr 27 10:35:00 2020', 'type': 'string', 'index': 4}, {'name': 'Uptime', 'value': '11 days 22 hours 50 minutes 51 seconds', 'type': 'string', 'index': 5}, {'name': 'Load average', 'value': '3.46, 2.34, 2.31', 'type': 'string', 'index': 6}, {'name': 'CPU usage', 'value': {'text': '38%', 'value': 38.403041825095}, 'type': 'progress', 'index': 7}, {'name': 'Memory usage', 'value': {'text': '54% of 11.68 GiB', 'value': 54}, 'type': 'progress', 'index': 8}]
2020-04-27 10:35:00 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OMV for openmediavault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/openmediavault/__init__.py", line 31, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 104, in async_update
    await self.hass.async_add_executor_job(self.get_hwinfo)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 133, in get_hwinfo
    int(self.data["hwinfo"]["memUsed"]) / int(self.data["hwinfo"]["memTotal"])
ZeroDivisionError: division by zero`
```

**Comment by tomaae** [comment]
Yeah, thats old OMV version which goes completely out of support soon. 
I fixed that issue in master, but not sure if it will work for you. OMV4 may use different fields for other attributes too.

**Comment by Skeletorjus** [comment]
Thanks. Applied your fix, and it at least gave me the sensors for CPU and memory, though both are sitting at 0% and no filesystem sensors were created.
As OMV4 is going out of support, the right course of action would maybe be to mark the integration as compatible with OMV5 or newer and for me to make the version jump :)

**Comment by tomaae** [comment]
I used [these steps](https://forum.openmediavault.org/index.php?thread/29547-solved-upgrade-from-omv-4-to-omv5/) and it was smooth transition. Even all settings stayed the same.
Of course, I set up DNS properly, not like that guide.

**Comment by Skeletorjus** [comment]
Very nice, that's very useful and will hopefully make the upgrade a less daunting task.

Thanks again. As the documentation has been changed to specify the version, I'll go ahead and close this issue.
