### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by handryck** [tomaae/homeassistant-openmediavault#36]
I have OpenMediaVault version 5.6.2-1 installed on a VM.
I'm trying to setup the HA integration by using the IP (port 80) and the same username I used before.
Keep in mind that this problem came out about three days ago and I don't know what the cause might be.

`Logger: aiohttp.server
Source: custom_components/openmediavault/omv_api.py:20
First occurred: 11:23:00 (25 occurrences)
Last logged: 11:25:38

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 150, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 158, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/openmediavault/config_flow.py", line 78, in async_step_user
    if not api.connect():
  File "/config/custom_components/openmediavault/omv_api.py", line 122, in connect
    cookies = load_cookies(self._cookie_jar_file)
  File "/config/custom_components/openmediavault/omv_api.py", line 20, in load_cookies
    return pickle_load(f)
EOFError: Ran out of input
`

**Comment by tomaae** [comment]
I have no idea what this could mean. Try restarting OMV middleware.

**Comment by handryck** [comment]
Hi, I restarted OMV and it's services tens of times and I still get the error. I even tried creating a different user and giving it all the permissions.

Scarica Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by tomaae** [comment]
try to delete file .omv_cookies.json. it could be corrupted.

**Comment by handryck** [comment]
> try to delete file .omv_cookies.json. it could be corrupted.

Where do I find the file?
I tried navigating into the custom_components and I cannot figure out where the file is.
I tried via console and file editor.
