### ISSUE TITLE
[Bug]OMV stopped working 

### ISSUE THREAD

**Issue by Dinth** [tomaae/homeassistant-openmediavault#37]
## Describe the issue

At some point OMV has stopped working - im not sure if it was after a system upgrade or something else - havent been checking OMV tab in HA for a while. 

## Software versions

 - Home Assistant version: 2021.3.3
 - openmediavault integration version: 1.1.5
 - openmediavault software version: 

## Traceback/Error logs

```
2021-03-10 18:01:36 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OMV for openmediavault
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/openmediavault/__init__.py", line 31, in async_setup_entry
await controller.async_hwinfo_update()
File "/config/custom_components/openmediavault/omv_controller.py", line 114, in async_hwinfo_update
await self.hass.async_add_executor_job(self.get_hwinfo)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/openmediavault/omv_controller.py", line 158, in get_hwinfo
source=self.api.query("System", "getInformation"),
File "/config/custom_components/openmediavault/omv_api.py", line 274, in query
return self.query(service, method, params, options)
File "/config/custom_components/openmediavault/omv_api.py", line 274, in query
return self.query(service, method, params, options)
File "/config/custom_components/openmediavault/omv_api.py", line 274, in query
return self.query(service, method, params, options)
[Previous line repeated 169 more times]
File "/config/custom_components/openmediavault/omv_api.py", line 273, in query
if self.connect():
File "/config/custom_components/openmediavault/omv_api.py", line 142, in connect
data = response.json()
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tomaae** [comment]
this looks like output from integration configuration, not configured integration. when do you get this error?

**Comment by Dinth** [comment]
On HA start. My OMV integration was configured and it was working fine, until at some point it stopped working with all the sensors being unavailable (havent updated OMV in a long time, but im regularly updating HA).
![Screenshot from 2021-03-12 08-59-25](https://user-images.githubusercontent.com/313674/110917118-75dc8100-8311-11eb-94ac-dbe67c7106d3.png)
![Screenshot from 2021-03-12 08-59-38](https://user-images.githubusercontent.com/313674/110917124-77a64480-8311-11eb-9dba-9048317b54c3.png)
