### ISSUE TITLE
[Question] ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by ikke68** [tomaae/homeassistant-openmediavault#4]
Hi,

I followed al you're steps , and also added the intergration for OMV. but there aren't any sensors showing up.. But there is something showing in the log file, see below. 

Log Details (ERROR)
Logger: homeassistant.config_entries
Source: custom_components/openmediavault/omv_controller.py:133
First occurred: 3:45:24 PM (1 occurrences)
Last logged: 3:45:24 PM

Error setting up entry OMV for openmediavault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/openmediavault/__init__.py", line 31, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 104, in async_update
    await self.hass.async_add_executor_job(self.get_hwinfo)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 133, in get_hwinfo
    int(self.data["hwinfo"]["memUsed"]) / int(self.data["hwinfo"]["memTotal"])
ZeroDivisionError: division by zero
Thanks for looking into it!!

**Comment by tomaae** [comment]
Thats probably same thing as #2
