### ISSUE TITLE
[Bug] Error while configuring integration on 2021.4

### ISSUE THREAD

**Issue by Gino1606** [tomaae/homeassistant-openmediavault#42]
Hi Tomaae, I ask you for help because I get this error when I try to integrate OMV. In your opinion, how could I solve? Thanks so much.
![Immagine 2021-04-11 155534](https://user-images.githubusercontent.com/73401150/114307502-33f55500-9ae0-11eb-9f7a-4df23888c62d.jpg)
![Immagine 2021-04-11 155609](https://user-images.githubusercontent.com/73401150/114307503-348deb80-9ae0-11eb-9434-986cc6353773.jpg)

**Comment by Gino1606** [comment]
![Immagine 2021-04-11 161722](https://user-images.githubusercontent.com/73401150/114307825-93a03000-9ae1-11eb-9465-591de29ca9c8.jpg)

**Comment by tomaae** [comment]
I see, its something HA changed in last release. I will have to look into changing setup procedure.

**Comment by Gino1606** [comment]
Thank you very much for everything and for the work you do ... We will wait for the update :-)

**Comment by BebeMischa** [comment]
I don't know, where you are living, tomaae, but you are welcome in Amsterdam for some coffe and testing ;-)

**Comment by judie07** [comment]
Hi Tomaae, I have the "same" problem!
 Version core-2021.4.3 
  Version supervisor-2021.03.9 
No 'version' key in the manifest file for custom integration 'openmediavault'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'openmediavault

**Comment by judie07** [comment]
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/openmediavault/omv_api.py, line 128: response = self._connection.post(
2021-04-12 17:56:15 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for openmediavault doing I/O at custom_components/openmediavault/omv_api.py, line 128: response = self._connection.post(
2021-04-12 17:56:15 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 107, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 214, in _async_handle_step
    result: dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/openmediavault/config_flow.py", line 78, in async_step_user
    if not api.connect():
  File "/config/custom_components/openmediavault/omv_api.py", line 128, in connect
    response = self._connection.post(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/openmediavault/omv_api.py, line 128: response = self._connection.post

**Comment by tomaae** [comment]
dont worry, I know what the issue is

**Comment by judie07** [comment]
sorry

**Comment by tomaae** [comment]
no worries.
fix is already released.

**Comment by judie07** [comment]
Thank you very much for the quick help.
Works perfectly again!

**Comment by Gino1606** [comment]
Thanks Tomaae now it works perfectly. You are a myth😊💪

**Comment by BebeMischa** [comment]
Your Co-Fi is on it's way... ;-)

**Comment by Gino1606** [comment]
A question Tomaae, I saw that the integration gives some disconnections (I am attaching the LOG) in your opinion how can it be solved? 
![Uploading Screenshot_2021-04-13-10-36-23-91_c3a231c25ed346e59462e84656a70e50.jpg…]()

**Comment by tomaae** [comment]
I cannot see that screenshot, it didnt upload right

**Comment by Gino1606** [comment]
Sorry, here's the screenshot. Practically it always repeats the same mistake. logs out and then comes back online.
Hope you can help me. Thanks so much...
![Immagine 2021-04-13 120145](https://user-images.githubusercontent.com/73401150/114535942-e0564900-9c50-11eb-95d7-2b63f3471a41.jpg)
![Immagine 2021-04-13 120301](https://user-images.githubusercontent.com/73401150/114535944-e0eedf80-9c50-11eb-81e5-e5671a921753.jpg)

**Comment by tomaae** [comment]
that part above that you cut off may be the problem. check your SSL settings are correct

**Comment by Gino1606** [comment]
Hi Tomaae, it's definitely my ssl configuration problem. Although I've only noticed it now. 
I use duckdns and can connect remotely via https. What do you think I can change to solve? If you need more screenshots with data, I'm at your disposal (I have attached that log that was cut).  It seems he wants an attribute that he thinks is wrong, but I don't understand. 
Thank you and good evening.
![Immagine 2021-04-13 225459](https://user-images.githubusercontent.com/73401150/114620988-77042380-9cac-11eb-8169-233cd5ffb1fc.jpg)

**Comment by tomaae** [comment]
try unchecking verify ssl when setting up the integration. that could help. or dont use ssl when connecting to omv if its in your network.

**Comment by Gino1606** [comment]
I tried but nothing to do. i checked the ssl and it is correct. I unchecked the checkbox when configuring the integration, but to no avail. I can't understand, may it be that I need to make some changes on OMV? I have no certificates set up and I am running home assistant in docker on OMV. Do you have any advice? It's a shame because the integration works perfectly but it gives me constant disconnections and fills my register with HA.

**Comment by tomaae** [comment]
it actually works? I though it does not work at all based on your screenshot.
If you can provide me first few minutes of debug log after HA restart, we cam find something out.

**Comment by Gino1606** [comment]
Okay, later I do everything and I update you on a new report. Thank you...
