### ISSUE TITLE
Unknown error when trying to set up openmediavault intergration

### ISSUE THREAD

**Issue by lineargraphics** [tomaae/homeassistant-openmediavault#58]
Here is the log
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/openmediavault/config_flow.py", line 75, in async_step_user
    if not await self.hass.async_add_executor_job(api.connect):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_api.py", line 128, in connect
    cookies = load_cookies(self._cookie_jar_file)
  File "/config/custom_components/openmediavault/omv_api.py", line 23, in load_cookies
    return pickle_load(f)
EOFError: Ran out of input

**Comment by tomaae** [comment]
looks like cookie corruption.
delete file .omv_cookies.json in your /config directory

**Comment by lineargraphics** [comment]
Thanks that helped but here is the new error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/openmediavault/__init__.py", line 23, in async_setup_entry
    await controller.async_hwinfo_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 112, in async_hwinfo_update
    await self.hass.async_add_executor_job(self.get_hwinfo)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 171, in get_hwinfo
    tmp = self.data["hwinfo"]["uptime"].split(" ")
AttributeError: 'float' object has no attribute 'split'

**Comment by tomaae** [comment]
that could mean that wrong data is received from OMV.
are you using OMV5? OMV6 wont work.
Also check OMV permissions for user you are using.

**Comment by lineargraphics** [comment]
Yeah OMV 6 so guess will have to wait for update huh. Thanks for the swift replies it worked great when I had OMV 5 installed.
