### ISSUE TITLE
[Bug] Cannot add integration if OMV requires HTTPS

### ISSUE THREAD

**Issue by Marte2007** [tomaae/homeassistant-openmediavault#6]
## Describe the issue
As in title, if OMV is configured to require HTTPS, you cannot configure the integration.
It works fine if you disable the forced SSL.
If you enable SSL after configuring the integration, the sensors stop working.

## How to reproduce the issue
- Enable "Force SSL/TLS" in OMV general settings
- Try to add the integration

## Software versions
 - Home Assistant version: 0.109.2
 - openmediavault integration version: v1.0.0
 - openmediavault software version: 5.3.5-1 (Usul)

## Additional context
My OMV is using a self-signed certificate, probably HASS doesn't trust it.
If that's the problem, is it possible to add a flag to bypass verification?

**Comment by tomaae** [comment]
Oh, sure. I will look into that.

**Comment by tomaae** [comment]
Solved in v1.0.1

**Comment by Marte2007** [comment]
Now I am able to add the integration, but I don't get any entity...
This time there's an error in the logs:
```
Logger: homeassistant.config_entries
Source: custom_components/openmediavault/helper.py:15
First occurred: 19:13:52 (1 occurrences)
Last logged: 19:13:52

Error setting up entry FileServer for openmediavault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/openmediavault/__init__.py", line 31, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/openmediavault/omv_controller.py", line 105, in async_update
    await self.hass.async_add_executor_job(self.get_hwinfo)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_controller.py", line 129, in get_hwinfo
    ensure_vals=[{"name": "memUsage", "default": 0},],
  File "/config/custom_components/openmediavault/helper.py", line 86, in parse_api
    data = fill_vals(data, entry, uid, vals)
  File "/config/custom_components/openmediavault/helper.py", line 225, in fill_vals
    data[_name] = from_entry(entry, _source, default=_default)
  File "/config/custom_components/openmediavault/helper.py", line 15, in from_entry
    if param not in entry:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by tomaae** [comment]
can you run it in debug?

**Comment by tomaae** [comment]
Found the issue, should be fine now in v1.0.2

**Comment by Marte2007** [comment]
It's working now, thanks
