### ISSUE TITLE
OMV 6 upgrade caused load fail

### ISSUE THREAD

**Issue by traveler2100** [tomaae/homeassistant-openmediavault#77]
Great integration, I've used it since it became available for OMV 6, but it stopped working after the last two HASS.IO core upgrades.  I tried to reload from scratch but get unknown error.  

HASS Info:

core-2022.4.2
--
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.108
CPU Architecture | x86_64

OMV Info:
Hostname
NASOMV.Workgroup
Version
6.0.20-1 (Shaitan)
Processor
Intel(R) Celeron(R) CPU N3050 @ 1.60GHz
Kernel
Linux 5.14.0-0.bpo.2-amd64

Traceback:
Logger: aiohttp.server
Source: custom_components/openmediavault/omv_api.py:24
Integration: OpenMediaVault ([documentation](https://github.com/tomaae/homeassistant-openmediavault), [issues](https://github.com/tomaae/homeassistant-openmediavault/issues))
First occurred: 9:43:40 AM (3 occurrences)
Last logged: 9:44:46 AM
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 206, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/openmediavault/config_flow.py", line 74, in async_step_user
    if not await self.hass.async_add_executor_job(api.connect):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_api.py", line 129, in connect
    if cookies := load_cookies(self._cookie_jar_file):
  File "/config/custom_components/openmediavault/omv_api.py", line 24, in load_cookies
    return pickle_load(f)
EOFError: Ran out of input

Thanks for great integration.

**Comment by tomaae** [comment]
looks like corrupted cookie
delete .omv_cookies file in /config

**Comment by traveler2100** [comment]
That was it.  All working fine.  Thanks!
