### ISSUE TITLE
error setup

### ISSUE THREAD

**Issue by korbendallas78** [tomaae/homeassistant-openmediavault#84]
## Software versions

 - Home Assistant version: 
 - openmediavault integration version: 
 - openmediavault software version:

**Comment by korbendallas78** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/openmediavault/config_flow.py", line 74, in async_step_user
    if not await self.hass.async_add_executor_job(api.connect):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_api.py", line 129, in connect
    if cookies := load_cookies(self._cookie_jar_file):
  File "/config/custom_components/openmediavault/omv_api.py", line 24, in load_cookies
    return pickle_load(f)
_pickle.UnpicklingError: pickle data was truncated

**Comment by korbendallas78** [comment]
omv 5.6.21-1 usul
Home Assistant Core 2022.6.
integration V1.3.0

**Comment by tomaae** [comment]
looks like corrupted cookie
delete .omv_cookies file in /config

**Comment by korbendallas78** [comment]
There is no that file

**Comment by korbendallas78** [comment]
Ok. Ifound it. It helped. Thank you

**Comment by korbendallas78** [comment]
Ok
