### ISSUE TITLE
[Bug] it is no longer possible to connect to OMV, since I updated Home Assistant.

### ISSUE THREAD

**Issue by JustinWalravens** [tomaae/homeassistant-openmediavault#88]
## Describe the issue

It is no longer possible to connect to OMV, since I updated Home Assistant.

## How to reproduce the issue

1. Update Home Assistant
2. Restart and no fonction

## Expected behavior

To be able to connect to OpenMediaVault.

## Screenshots

![Capture d’écran 2022-09-08 à 00 22 51](https://user-images.githubusercontent.com/94064573/188994174-41b04351-d396-472b-9da6-819ea1e136b6.png)
![Capture d’écran 2022-09-08 à 00 23 07](https://user-images.githubusercontent.com/94064573/188994178-acd6a2f4-da2e-464e-bef8-b1accd7acbe6.png)

## Software versions

 - Home Assistant version: e.g. HA 2022.9.0 
 - openmediavault integration version: e.g. v1.3.0 
 - openmediavault software version: e.g. v6.0.38-1 

## Traceback/Error logs

 Cette erreur provient d'une intégration personnalisée

Logger: aiohttp.server
Source: custom_components/openmediavault/omv_api.py:24
Integration: OpenMediaVault (documentation, issues)
First occurred: 00:06:37 (3 occurrences)
Last logged: 00:06:48

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 178, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/openmediavault/config_flow.py", line 74, in async_step_user
    if not await self.hass.async_add_executor_job(api.connect):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmediavault/omv_api.py", line 129, in connect
    if cookies := load_cookies(self._cookie_jar_file):
  File "/config/custom_components/openmediavault/omv_api.py", line 24, in load_cookies
    return pickle_load(f)
EOFError: Ran out of input

**Comment by tomaae** [comment]
try deleting cookie file. its probably corrupted

**Comment by JustinWalravens** [comment]
What is its name and location?

**Comment by tomaae** [comment]
.omv_cookies file in /config

**Comment by JustinWalravens** [comment]
This file is not exist.

**Comment by tomaae** [comment]
not in custom components, thats just code. its directly in /config
it starts with dot, so it may be hidden in browser

**Comment by JustinWalravens** [comment]
Ok, sorry. 
It's working.
Thanks

**Comment by tomaae** [comment]
np
